spring:

  application:
    name: example-sms

  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 2000000

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

server:
  port: 8080

logging:
  level:
    root: info
    org.hibernate.SQL: debug

# Solapi SMS 설정
solapi:
  api-key: ${SOLAPI_API_KEY}
  api-secret: ${SOLAPI_API_SECRET}
  sender: ${SOLAPI_SENDER_NUMBER}